CarSalesAgencyWeb/Areas/Admin/Controllers/BrandController.cs
using CarSalesAgency.DataAccess.Repository.IRepository;
using CarSalesAgency.Models;
using CarSalesAgency.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarSalesAgencyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class BrandController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;


        public BrandController(IUnitOfWork UnitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _UnitOfWork = UnitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Get
        public IActionResult Upsert(int? Id)
        {
            Brand brand = new();
            if (Id == null || Id == 0)
            {
                //Create brand
                return View(brand);
            }
            else
            {
                //Update product
                brand = _UnitOfWork.Brand.GetFirstOrDefault(u => u.Id == Id);
                return View(brand);
            }
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Brand obj, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    //Generate new file name
                    string FileName = Guid.NewGuid().ToString();
                    //find the location where the files should be uploaded
                    var uploads = Path.Combine(wwwRootPath, @"images\brands");
                    //keep same extension
                    var extension = Path.GetExtension(file.FileName);

                    //update the image - Check if there is an image
                    if (obj.ImgUrl != null)
                    {
                        //old image path
                        var oldImagePath = Path.Combine(wwwRootPath, obj.ImgUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    //copy the file uploaded inside the product folder
                    using (var fileStreams = new FileStream(Path.Combine(uploads, FileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    //what we will save in the DB
                    obj.ImgUrl = @"\images\brands\" + FileName + extension;
                }
                if (obj.Id == 0)
                {
                    _UnitOfWork.Brand.Add(obj);

                }
                else
                {
                    _UnitOfWork.Brand.Update(obj);
                }
                _UnitOfWork.Save();
                TempData["success"] = "brand created successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var brandtList = _UnitOfWork.Brand.GetAll();
            return Json(new { data = brandtList });
        }
        //POST
        [HttpDelete]
        public IActionResult Delete(int? Id)
        {
            var Obj = _UnitOfWork.Brand.GetFirstOrDefault(u => u.Id == Id);
            if (Obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, Obj.ImgUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _UnitOfWork.Brand.Remove(Obj);
            _UnitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion
    }
}

CarSalesAgencyWeb/Areas/Admin/Views/Brand/Index.cshtml
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Brand List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Brand" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create Brand
            </a>
        </div>
    </div>
    <br /> <br />

<table id="tblData" class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th width="60%">
                Name
            </th>
            <th></th>
        </tr>
    </thead> 
</table>
</div>

@section Scripts{
    <script src="~/js/brand.js"></script>
}

CarSalesAgencyWeb/Areas/Admin/Views/Brand/Upsert.cshtml
@model CarSalesAgency.Models.Brand

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input asp-for="@Model.Id" hidden/>
    <input asp-for="@Model.ImgUrl" hidden/>

    <div class="row">
        <div class="col-10">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">@(Model.Id!=0?"Update": "Create") Brand</h2>
                    <hr />
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.Name"></label>
                    <input  asp-for="@Model.Name" class="form-control"/>
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.ImgUrl"></label>
                    <input id="UploadBox" type="file" name="file" class="form-control"/>
                </div>
                <div class="col-12">
                    @if (Model.Id != 0)
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px" >Update</button>
                    }
                    else
                    {
                        <button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width:150px">Create</button>
                    }
                    <a asp-controller="Brand" asp-action="Index" class="btn btn-secondary" style="width:150px">
                        Back to list
                    </a>
                </div>
        
            </div>
        </div>
        <div class="col-2 mt-4">
            <img src="@Model.ImgUrl"
                style="width: 100%;border-radius:5px;border:1px solid #bbb9b9"/>
        </div>
    </div>

</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial"/>
    }
    <script>
        function ValidateInput(){
            if (document.getElementById("UploadBox").value == "") {
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Pleas upload an Image!',
                });
                return false;
            }
            return true;
        }
    </script>
}